<?php
/**
 * Foodgo Gourmet Food Ordering Platform
 * Sample Configuration Template (Databaseless FileStore Engine)
 * 
 * NOTE: This file is automatically generated upon running install.php.
 * All persistent data is stored securely in the /data/ JSON store.
 */

if (!defined('FOODGO_ACCESS')) {
    define('FOODGO_ACCESS', true);
}

return [
    'app' => [
        'name'        => 'Foodgo',
        'url'         => 'http://localhost',
        'env'         => 'production', // 'production' or 'development'
        'debug'       => false,
        'secret'      => 'CHANGE_ME_TO_A_CRYPTOGRAPHICALLY_SECURE_RANDOM_KEY',
        'timezone'    => 'Asia/Kolkata',
        'currency'    => 'INR (₹)',
    ],
    'storage' => [
        'engine'      => 'FileStore',
        'data_dir'    => __DIR__ . '/../data',
        'backup_dir'  => __DIR__ . '/../backups',
    ],
    'upload' => [
        'max_size_mb' => 20,
        'allowed_image_types' => ['image/jpeg', 'image/png', 'image/webp', 'image/gif'],
        'allowed_audio_types' => ['audio/webm', 'audio/mp4', 'audio/ogg', 'audio/wav', 'audio/mpeg'],
    ],
    'installed' => false,
];
